spring:
  application:
    name: cta4j-api
app:
  rollbar:
    environment: ${APP_ROLLBAR_ENVIRONMENT}
    code-version: ${APP_ROLLBAR_CODE_VERSION}
  aws:
    region: ${AWS_REGION}
    secrets-manager:
      secret-id: ${APP_AWS_SECRETS_MANAGER_SECRET_ID}
    dynamodb:
      tables:
        routes: ${APP_AWS_DYNAMODB_TABLES_ROUTES}
        route-directions: ${APP_AWS_DYNAMODB_TABLES_ROUTE_DIRECTIONS}
        route-stops: ${APP_AWS_DYNAMODB_TABLES_ROUTE_STOPS}
        stations: ${APP_AWS_DYNAMODB_TABLES_STATIONS}
  cors:
    allowed-origins:
      - https://cta4j.app
      - https://www.cta4j.app
      - https://cta4j.com
      - https://www.cta4j.com
      - https://chat.openai.com
    allowed-methods:
      - GET
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
  cache:
    names:
      - routes
      - directions
      - stops
      - stations
    ttl-seconds: ${APP_CACHE_TTL_SECONDS:86400}
